version: '3.0'

services:
  webapp:
    image: node:19
    container_name: multiple-choice-frontend 
    restart: always
    volumes:
      - ./multiple-choice-frontend:/app
    ports:
      - 3001:3000
    user: node
    command: >
      sh -c " 
        cd /app &&
        npm install &&
        npm start &&
        tail -f /dev/null
      "
  server:
    image: python:latest
    container_name: multiple-choice-backend
    volumes:
      - ./multiple-choice-backend:/app
    ports:
      - 2911:2910
    command: >
      sh -c "
        cd /app &&
        python -m venv .venv
        . .venv/bin/activate &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        python manage.py makemigrations && 
        python manage.py migrate && 
        uvicorn app.asgi:application --host 0.0.0.0 --port 2910 --reload &&
        tail -f /dev/null
      "
    depends_on:
      db:
        condition: service_healthy

    restart: always
  db:
    image: mysql:latest
    container_name: multiple-choice-mysql 
    volumes:
      - ./.db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_HOST=%
      - MYSQL_HOST=localhost

    healthcheck:
      test: mysqladmin ping
      timeout: 20s
      retries: 10

    restart: always